
name: 'churn_prediction'
version: '1.0.0'
config-version: 2

profile: 'churn_prediction'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  churn_prediction:
    staging:
      +materialized: view
      +schema: churn_features
    features:
      +materialized: table
      +schema: churn_features
